runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /jspm_packages
  static_dir: app/jspm_packages

- url: /assets
  static_dir: app/assets

- url: /src
  static_dir: app/src

- url: /config\.js
  static_files: app/config.js
  upload: config\.js

- url: /.*
  script: tournament.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
